#!/bin/sh
mkdir -p /local/opt

curl -sL https://github.com/lih/BHR/releases/download/release-capricon-0.12.1/capricon.linux.x86_64.tar.xz | \
    tar -xJ -C /local/opt

ln -s /local/opt/capricon-0.12.1 /usr/bin/capricon
