#!/bin/bash
echo
echo ---
capricon_version="$(capricon src/pages/prelude <<< "version print")"
printf "capricon-version: \"%s\"\n" "$capricon_version"
printf "pandoc-version: \"%s\"\n" $(pandoc --version | head -1 | cut -d' ' -f2)
printf "noise-image-url: \"data:image/png;base64,%s\"\n" "$(base64 -w0 "$1")"
printf "steps-image-url: \"data:image/png;base64,%s\"\n" "$(base64 -w0 "$2")"
printf "prelude-text: '<script id=\"capricon-prelude\" type=\"text/plain\">%s</script>'\n" "$(sed ':loop;$!{N;bloop};'s/\'/\'\'/g';s/\n/ /gm;s/\\/\\\\/g;s/\$/\\$/g' "$3")"
echo --- 
echo
for i in "$PAGES_ROOT"/*.md; do
    i=${i#"$PAGES_ROOT/"}; i=${i%.md}
    printf "[:%s]: %s.html\n" $i $i
done
echo
cat <<EOF
[capricon-linux]: https://github.com/lih/BHR/releases/download/release-capricon-0.12.2.1/capricon.linux.x86_64.tar.xz
[capricon-macos]: https://github.com/lih/BHR/releases/download/release-capricon-0.12.2.1/capricon.osx.x86_64.tar.xz
EOF

