#!/bin/bash
echo
echo --- ; capricon src/pages/prelude <<< "version \"capricon-version: %s\n\" printf" 
printf "pandoc-version: "; pandoc --version | head -1 | cut -d' ' -f2
printf "noise-image-url: \"data:image/png;base64,%s\"\n" "$(base64 -w0 "$1")"
printf "steps-image-url: \"data:image/png;base64,%s\"\n" "$(base64 -w0 "$2")"
printf "prelude-text: '%s'\n" "$(sed ':loop;$!{N;bloop};s/'\''/'\'\''/g;s/\n/ /gm;s/\\/\\\\/g' "$3")"
echo --- 
echo
for i in "$PAGES_ROOT"/*.md; do
    i=${i#"$PAGES_ROOT/"}; i=${i%.md}
    printf "[:%s]: %s.html\n" $i $i
done
echo
