#!/bin/bash
if [ "$AUTOCOMMIT" = true ]; then
    (
	export GIT_DIR=src/pages/.git GIT_WORK_TREE=src/pages
	git add -A
	git commit -am "Pages updated (on $(date))"
    )
    git add -A
    git commit -am "Pages updated (on $(date))"
    git push
fi
