#!/bin/bash
(
    export GIT_DIR=.autocommit/src/pages/.git GIT_WORK_TREE=src/pages
    git add -A
    git commit -am "Autocommit on $(date)"
    git push
)
(
    export GIT_DIR=.autocommit/.git
    git add -A
    git commit -am "Autocommit on $(date)"
    git push
)
